### ISSUE TITLE
February 05, 2020 | Code-Review : The Poodles

### ISSUE THREAD

**Issue by Flakster** [sz16900/enumerables#1]
Good intro to Ruby.  Thanks for sharing your experience @sz16900 . I like the contents of your array

https://github.com/sz16900/enumerables/blob/dd64ae86e3148e12f448c26e86bc7b6a3b6a6ac0/testing.rb#L26

**Comment by jabichris** [comment]
Nice work @sz16900, what you can work on in the future is to make sure your commits are descriptive.
<img width="1058" alt="Screen Shot 2020-02-05 at 16 33 40" src="https://user-images.githubusercontent.com/33568373/73850982-6d279a80-4835-11ea-900c-4f68a059eafa.png">

**Comment by Meltrust** [comment]
Nice work, and fascinating thinking!  Maybe you could comment a little more in your code so when sharing to us it is easier to understand.

**Comment by sz16900** [comment]
:)

**Comment by kirokoNjenga** [comment]
nice work
